import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ColorProvider } from "@/context/color-context";
import { PointsProvider } from "@/context/points-context";
import { MessageProvider } from "@/context/message-context";
import { TimerProvider } from "@/context/timer-context";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <ColorProvider>
          <PointsProvider>
            <TimerProvider>
              <MessageProvider>
                {children}
              </MessageProvider>
            </TimerProvider>
          </PointsProvider>
        </ColorProvider>
      </body>
    </html>
  );
}
